[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { workspace = true }
tx = { workspace = true }
schedule = { workspace = true }
network = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
primitives = { workspace = true }
chain = { workspace = true }
thiserror = { workspace = true }
contract = { workspace = true }
platform = { workspace = true }
account = { workspace = true }
apps = { workspace = true }
bcs = { workspace = true }
tokio = { workspace = true }

risc0-zkvm = { workspace = true}
risc0-build = { workspace = true }
risc0-groth16 = { workspace = true }
risc0-zkp = { workspace = true }
risc0-binfmt = { workspace = true }
risc0-core = { workspace = true }

risc0-zkvm-platform = { workspace = true }
risc0-zkos-v1compat = { workspace = true }

risc0-circuit-keccak = { workspace = true }
risc0-circuit-recursion = { workspace = true }
risc0-circuit-rv32im = { workspace = true }

risc0-circuit-keccak-sys = { workspace = true }
risc0-circuit-recursion-sys = { workspace = true }
risc0-circuit-rv32im-sys = { workspace = true }

[features]
default = []
cuda = ["risc0-zkvm/cuda", "risc0-zkvm/prove"]