[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { workspace = true }
tx = { workspace = true }
schedule = { workspace = true }
network = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
risc0-zkvm = { workspace = true}
hex = { workspace = true }
primitives = { workspace = true }
chain = { workspace = true }
thiserror = { workspace = true }
contract = { workspace = true }
platform = { workspace = true }
account = { workspace = true }
apps = { workspace = true }
bcs = { workspace = true }
tokio = { workspace = true }

[features]
default = []
cuda = ["risc0-zkvm/cuda", "risc0-zkvm/prove"]