[package]
name = "methods"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
risc0-build = { workspace = true }
risc0-groth16 = { workspace = true }
risc0-zkp = { workspace = true }
risc0-binfmt = { workspace = true }
risc0-core = { workspace = true }

risc0-zkvm-platform = { workspace = true }
risc0-zkos-v1compat = { workspace = true }

risc0-circuit-keccak = { workspace = true }
risc0-circuit-recursion = { workspace = true }
risc0-circuit-rv32im = { workspace = true }

risc0-circuit-keccak-sys = { workspace = true }
risc0-circuit-recursion-sys = { workspace = true }
risc0-circuit-rv32im-sys = { workspace = true }

[package.metadata.risc0]
methods = ["pass", "ledger_guest", "smallbank_guest", "fibonacci"]