[package]
name = "network"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = { version = "0.56", features = [
    "tokio", "noise", "yamux", "macros",
    "tcp", "dns", "websocket", "quic",
    "identify", "kad", "mdns", "ping", "gossipsub",
] }
tokio = { workspace = true }
futures = "0.3.30"
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
primitives = { workspace = true }
serde_json = { workspace = true }
serde = { version = "1.0.226", features = ["derive"] }