[package]
name = "network"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = { version = "0.56", features = [
    "tokio", "noise", "yamux", "macros",
    "tcp", "dns", "websocket", "quic",
    "identify", "kad", "mdns", "ping", "gossipsub",
] }
tokio = { workspace = true }
futures = "0.3.30"
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
primitives = { workspace = true }
spec = { workspace = true }
tx = { workspace = true }
hex = { workspace = true }
account = { workspace = true }