[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { workspace = true }
network = { workspace = true }
contract = { workspace = true }
account = { workspace = true }
risc0-zkvm = { workspace = true}
task = { workspace = true }
engine = { workspace = true }
tx = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
schedule = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
primitives = { workspace = true }
serde = { workspace = true }
apps = { workspace = true }

[features]
default = []
cuda = ["risc0-zkvm/cuda", "risc0-zkvm/prove"]