[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
ledger = { workspace = true }
smallbank = { workspace = true }
account = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
spec = { workspace = true }
platform = { workspace = true }
rand_core = { workspace = true }
apps = { workspace = true }