chain_id: 1000
slot_secs: 8
tx_capacity: 100
consensus:
  protocol: "cft"
  leader_id: "12D3KooWGY8Jj1KCjfa9ib6njuufGHsoBWrRrr4TMEJrgcBjsThE"
  members:
    - "12D3KooWGY8Jj1KCjfa9ib6njuufGHsoBWrRrr4TMEJrgcBjsThE" # smolensk
    - "12D3KooWEB9JUhgjPUuR5QVeokUNeRSpjcxxGaELnLvydLTpCFUZ" # mecca
    - "12D3KooWHDdwT22WmhiVVvyWQ85wtDEsBX7ERAhGZfYigJL7vzA9" # kol-server
prove:
  mode: "native" # "native" | "simulate"
  latency: 500

dispatch:
  window_size: 16
  ema_k: 8
  # max_score 10000
  score:
    timeliness:
      timeout: 0
    integrity:
      fake: 4000

queue:
  discipline: "edf_spt" # fcfs | spt | edf | spt_edf | edf_spt

