chain_id: 1000
slot_secs: 12
enable_prove_receipt_recording: false
prove_receipt_csv: "prove-receipt" # cycles, cycle_label, scale, prove_time, receipt_size
enable_verify_receipt_recording: false
verify_receipt_csv: "verify-receipt" # cycles, verify_time,
enable_validate_block_recording: false
validate_block_csv: "validate-block"
consensus:
  mode: "simulate" # "native" | "simulate"
  simulate_size: 100
  simulate_size_array: [1, 1, 10, 100, 1000, 10000]
  protocol: "solo"
  tx_capacity: 10000
  leader_id: "12D3KooWGY8Jj1KCjfa9ib6njuufGHsoBWrRrr4TMEJrgcBjsThE"
  members:
    - "12D3KooWGY8Jj1KCjfa9ib6njuufGHsoBWrRrr4TMEJrgcBjsThE" # smolensk
    - "12D3KooWEB9JUhgjPUuR5QVeokUNeRSpjcxxGaELnLvydLTpCFUZ" # mecca
    - "12D3KooWHDdwT22WmhiVVvyWQ85wtDEsBX7ERAhGZfYigJL7vzA9" # kol-server
prove:
  mode: "native" # "native" | "simulate"
  scheme: "succinct" # "succinct" | "fast" | "groth16"
  latency: 50
  offset: 5

dispatch:
  window_size: 16
  ema_k: 8
  # max_score 10000
  score:
    timeliness:
      timeout: 0
    integrity:
      fake: 4000

queue:
  discipline: "edf_spt" # fcfs | spt | edf | spt_edf | edf_spt

