[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
bench = { workspace = true }
directories = { workspace = true }
rocksdb = { version = "0.24"}
thiserror = { workspace = true }
once_cell = { workspace = true }
tempfile = { version = "3"}
arc-swap = "1.7.1"
clap = { workspace = true }
chain = { workspace = true }
contract = { workspace = true }
account = { workspace = true }
primitives = { workspace = true }
spec = { workspace = true }
apps = { workspace = true }
platform = { workspace = true }