[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { workspace = true }
server = { workspace = true }
tx = { workspace = true }
network = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
risc0-zkvm = { workspace = true, features = ["cuda"] }
clap = { workspace = true }
dotenvy = { workspace = true }
primitives = { workspace = true }
chain = { workspace = true }
contract = { workspace = true }
platform = { workspace = true }
account = { workspace = true }
apps = { workspace = true }