[package]
name = "executor"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { workspace = true }
server = { workspace = true }
tx = { workspace = true }
schedule = { workspace = true }
network = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
engine = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
platform = { workspace = true }
account = { workspace = true }

[features]
default = []                         # 看你需不需要默认 feature
cuda = ["engine/cuda"]