[package]
name = "tx"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
account = { workspace = true }
ed25519-dalek = { workspace = true }
rand_core = { workspace = true }
primitives = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
bcs = { version = "0.1" }
serde_with = "3.15"
hex = { workspace = true }