[package]
name = "tx"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
account = { workspace = true }
rand_core = { workspace = true }
primitives = { workspace = true }
thiserror = { workspace = true }
bcs = { workspace = true }
serde_with = { workspace = true }
hex = { workspace = true }
chain = { workspace = true }
