[package]
name = "app"
version = "0.1.0"
edition = "2024"
authors = ["marmot"]

[dependencies]
tx = { workspace = true }
chain = { workspace = true }
reqwest = { version = "0.12" }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
account = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }