[package]
name = "chain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
tx = { workspace = true }
account = { workspace = true }
primitives = { workspace = true }
thiserror = { workspace = true }
bcs = { workspace = true }
sha2 = { workspace = true }
spec = { workspace = true }
platform = { workspace = true }